RecrApp/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include(("apps.users.urls", "users"), namespace="users")),
    path('', include(("apps.home.urls", "home"), namespace="home")),
    path('jobs/', include(("apps.jobs.urls", "jobs"), namespace="jobs")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/jobs/urls.py
from django.urls import path

from .views import ListJobApplicationView, CreateJobApplicationView, jobs_home_view, \
    ResumeListView

urlpatterns = [
    path('', jobs_home_view, name='home'),
    path('list/', ListJobApplicationView.as_view(), name='list_of_applications'),
    path('create/', CreateJobApplicationView.as_view(), name='create_application'),
    path('resume_list/', ResumeListView.as_view(), name='resume_list'),
]

apps/users/urls.py
from django.urls import path
from django.views.generic import TemplateView
from django.contrib.auth.views import LogoutView
from .views import CustomLoginView, CustomRegisterView, ActivateAccount, \
    UserDetailView, UserUpdateView

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('register/', CustomRegisterView.as_view(), name='register'),
    path('logout/', LogoutView.as_view(next_page='home:home'), name='logout'),
    path('activate/<uidb64>/<token>/', ActivateAccount.as_view(), name='activate'),
    path(
        'account_activation_sent/',
        TemplateView.as_view(template_name='users/account_activation_sent.html'),
        name='account_activation_sent'
    ),
    path('profile/', UserDetailView.as_view(), name='profile'),
    path('update_profile/', UserUpdateView.as_view(), name='update_profile'),
]

apps/users/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from apps.users.utils import user_profile_picture_path


class UserProfile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name='userprofile'
    )
    phone_number = PhoneNumberField(null=True, unique=True)
    country = models.CharField(max_length=20, null=True)
    city = models.CharField(max_length=20, null=True)
    profile_picture = models.ImageField(
        upload_to=user_profile_picture_path,
        blank=True,
        null=True,
    )

    def __str__(self):
        return f"{self.user.username}'s Profile"


class SiteLinks(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sitelinks')
    name = models.CharField(max_length=50)
    url = models.URLField(max_length=200, unique=True)
    description = models.TextField(null=True, blank=True)

    def __str__(self):
        return f"{self.name} - {self.user.username}"

apps/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User

from .models import UserProfile, SiteLinks


class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField()
    password1 = forms.CharField()
    password2 = forms.CharField()
    email = forms.EmailField(required=True)
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)
    phone_number = forms.CharField(required=False)
    country = forms.CharField(required=False)
    city = forms.CharField(required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = User
        fields = (
            "username", "email", "first_name", "last_name", "password1",
            "password2", "phone_number", "country", "city", "profile_picture"
        )

    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data.get('first_name', '')
        user.last_name = self.cleaned_data.get('last_name', '')
        if commit:
            user.save()
            UserProfile.objects.create(
                user=user,
                phone_number=self.cleaned_data.get('phone_number', ''),
                country=self.cleaned_data.get('country', ''),
                city=self.cleaned_data.get('city', ''),
                profile_picture=self.cleaned_data.get('profile_picture'),
            )
        return user

    def clean_username(self):
        username = self.cleaned_data.get('username').lower()
        if User.objects.filter(username__iexact=username).exists():
            raise forms.ValidationError("A user with that username already exists.")
        return username

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name', '')
        return first_name.capitalize()

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name', '')
        return last_name.capitalize()

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number', '')
        return phone_number

    def clean_email(self):
        email = self.cleaned_data.get('email').lower()
        if User.objects.filter(email__iexact=email).exists():
            raise forms.ValidationError("A user with that email already exists.")
        return email


class CustomUpdateUserForm(UserChangeForm):
    first_name = forms.CharField(required=False)
    last_name = forms.CharField(required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name')

    def clean_first_name(self):
        first_name = self.cleaned_data.get('first_name')
        if first_name is None or first_name == '':
            return self.instance.first_name  # keep existing value
        return first_name.capitalize()

    def clean_last_name(self):
        last_name = self.cleaned_data.get('last_name')
        if last_name is None or last_name == '':
            return self.instance.last_name  # keep existing value
        return last_name.capitalize()


class UserProfileUpdateForm(forms.ModelForm):
    phone_number = forms.CharField(required=False)
    country = forms.CharField(required=False)
    city = forms.CharField(required=False)
    profile_picture = forms.ImageField(required=False)

    class Meta:
        model = UserProfile
        fields = ['phone_number', 'country', 'city', 'profile_picture']

    def clean_phone_number(self):
        phone_number = self.cleaned_data.get('phone_number')
        if phone_number is None or phone_number == '':
            return self.instance.phone_number
        return phone_number

    def clean_country(self):
        country = self.cleaned_data.get('country')
        if country is None or country == '':
            return self.instance.country
        return country

    def clean_city(self):
        city = self.cleaned_data.get('city')
        if city is None or city == '':
            return self.instance.city
        return city


class SiteLinksForm(forms.ModelForm):
    name = forms.CharField(required=True)
    url = forms.URLField(required=True, assume_scheme='https')
    description = forms.CharField(required=False)

    class Meta:
        model = SiteLinks
        fields = ['name', 'url', 'description']

apps/users/views.py
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.tokens import default_token_generator
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.sites.shortcuts import get_current_site
from django.core.mail import EmailMessage
from django.forms import modelformset_factory
from django.shortcuts import render, redirect
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.utils.encoding import force_str, force_bytes
from django.utils.http import urlsafe_base64_decode, urlsafe_base64_encode
from django.views import View
from django.views.generic import DetailView, UpdateView
from django.views.generic.edit import FormView

from .forms import CustomUserCreationForm, CustomUpdateUserForm, \
    UserProfileUpdateForm, SiteLinksForm
from .models import UserProfile, SiteLinks


class CustomLoginView(LoginView):
    template_name = 'users/login.html'
    redirect_authenticated_user = True
    authentication_form = AuthenticationForm

    def get_success_url(self):
        return reverse_lazy('jobs:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add your custom context variables here
        context['title'] = 'Please Log In'
        context['button_info'] = 'Log In'
        return context


class CustomLogoutView(LogoutView):
    success_url = reverse_lazy('home:home')

    def get_success_url(self):
        return reverse_lazy('home:home')


class CustomRegisterView(FormView):
    form_class = CustomUserCreationForm
    redirect_authenticated_user = True
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:account_activation_sent')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add your custom context variables here
        context['title'] = 'Please Register'
        context['button_info'] = 'Register'
        return context

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()

            UserProfile.objects.create(
                user=user,
                phone_number=form.cleaned_data.get('phone_number', ''),
                country=form.cleaned_data.get('country', ''),
                city=form.cleaned_data.get('city', ''),
                profile_picture=form.cleaned_data.get('profile_picture'),
            )

            # Send activation email (your existing code)
            current_site = get_current_site(request)
            mail_subject = 'Activate your account'
            message = render_to_string('users/activation_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': default_token_generator.make_token(user),
            })
            EmailMessage(mail_subject, message, to=[user.email]).send()

            return redirect(self.success_url)

        return self.render_to_response(
            self.get_context_data(form=form)
        )


class ActivateAccount(View):
    def get(self, request, uidb64, token, *args, **kwargs):
        try:
            uid = force_str(urlsafe_base64_decode(uidb64))
            user = User.objects.get(pk=uid)
        except (TypeError, ValueError, OverflowError, User.DoesNotExist):
            user = None

        if user is not None and default_token_generator.check_token(user, token):
            user.is_active = True
            user.save()
            # Optional: login user here
            return redirect('users:login')
        else:
            return render(request, 'users/activation_invalid.html')


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    template_name = 'users/profile.html'
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Add your custom context variables here

        profile = self.request.user.userprofile
        site_links = self.request.user.sitelinks.all()
        context['site_links'] = site_links
        context['profile'] = profile
        return context


class UserUpdateView(LoginRequiredMixin, UpdateView):
    template_name = 'users/update_profile.html'
    model = User
    form_class = CustomUpdateUserForm
    second_form_class = UserProfileUpdateForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        return self.request.user

    def get_formset_class(self):
        return modelformset_factory(
            SiteLinks,
            form=SiteLinksForm,
            extra=0,
            can_delete=True
        )

    def get_formset(self):
        FormsetClass = self.get_formset_class()
        if self.request.method == "POST":
            return FormsetClass(
                self.request.POST,
                queryset=self.get_queryset()
            )
        return FormsetClass(queryset=self.get_queryset())

    def get_queryset(self):
        return self.request.user.sitelinks.all()

    def get_second_form(self):
        if self.request.method == "POST":
            return self.second_form_class(
                self.request.POST,
                self.request.FILES,
                instance=self.request.user.userprofile
            )
        return self.second_form_class(instance=self.request.user.userprofile)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["second_form"] = kwargs.get("second_form", self.get_second_form())
        context["formset"] = kwargs.get("formset", self.get_formset())
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()  # Ensure we have the user object
        form = self.get_form()
        second_form = self.get_second_form()
        formset = self.get_formset()

        if form.is_valid() and second_form.is_valid() and formset.is_valid():
            # Save user form
            form.save()

            # Save user profile form
            second_form.save()

            instances = formset.save(commit=False)
            for obj in instances:
                obj.user = self.request.user
                obj.save()
            # delete objects if marked
            for obj in formset.deleted_objects:
                obj.delete()
            return redirect(self.get_success_url())
        return self.render_to_response(
            self.get_context_data(form=form, second_form=second_form, formset=formset)
        )

apps/users/templates/users/account_activation_sent.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Wysłano na email</title>
</head>
<body>
    Wysłano link aktywacyjny na email
</body>
</html>

apps/users/templates/users/activation_email.html
Hi {{ user.username }},

Thank you for registering at {{ domain }}.

Please click the link below to activate your account:

http://{{ domain }}{% url 'users:activate' uidb64=uid token=token %}

If you did not sign up for this account, please ignore this email.

Best regards,
The {{ domain }} Team

apps/users/templates/users/after_login_base.html
{% extends "base.html" %}
{% load static %}

{% block title %} Home Page {% endblock title %}

{% block navbar_content %}
  <a class="navbar-brand ms-2" href={% url 'home:home' %}>Home</a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Manage Your Job Applications
        </a>
        <ul class="dropdown-menu">
          <li><a class="dropdown-item" href={% url 'jobs:create_application' %}>Create job application</a></li>
          <li><a class="dropdown-item" href={% url 'jobs:list_of_applications' %}>List job applications</a></li>
          <li><a class="dropdown-item" href={% url 'jobs:resume_list' %}>Resume list</a></li>
          <li><hr class="dropdown-divider"></li>
          <li><a class="dropdown-item" href="#">Analysis</a></li>
        </ul>
      </li>
    </ul>
    <div  class="navbar-nav ms-auto mb-2 mb-lg-0 me-2">
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search"/>
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    <div class="d-flex align-items-center ms-2">

      <!-- Profile dropdown -->
      <div class="dropdown">
        <a
          href="#"
          class="d-block link-dark text-decoration-none dropdown-toggle"
          id="profileDropdown"
          data-bs-toggle="dropdown"
          aria-expanded="false"
        >
          <img
            src="{% if user.userprofile.profile_picture %}
              {{ user.userprofile.profile_picture.url }}
              {% else %}
              {% static 'images/random_person.png' %}
              {% endif %}"
            alt="User Profile"
            width="40"
            height="40"
            class="rounded-circle"
          />
        </a>
        <ul class="dropdown-menu dropdown-menu-end text-small" aria-labelledby="profileDropdown">
            <li><a class="dropdown-item" href={% url 'users:profile' %}>Profile</a></li>
            <li><a class="dropdown-item" href="#">Settings</a></li>
            <li><hr class="dropdown-divider"></li>
            <li>
                <form method="post" action="{% url 'users:logout' %}">
                {% csrf_token %}
                <button class="dropdown-item">
                    Sign out
                </button>
                </form>
            </li>
        </ul>
      </div>
    </div>
    
  </div>
{% endblock navbar_content %}

apps/users/templates/users/before_login_base.html
{% extends "home/home.html" %}
{% load static %}

{% block title %} Home Page {% endblock title %}

{% block main_content %} {% endblock main_content %}

apps/users/templates/users/profile.html
{% extends "users/after_login_base.html" %}
{% load static %}
{% load phone_number_extras %}

{% block main_content %}
<div class="container-lg border border-3 rounded-5 p-4 mx-auto bg-light mt-4 mb-4" style="min-height: 60vh;">
    <div class="container-lg border border-3 rounded-5 p-4 mx-auto bg-white m-4">
        <div class="row mb-3">
            <div class="col col-8">
                <div class="h2 border-bottom pb-3 mb-3 display-2">
                    Account Information
                </div>
                <div class="row mb-1 ms-3">
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">First Name</label>
                        <div class="form-control-plaintext">{{ user.first_name }}</div>
                    </div>
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">Last Name</label>
                        <div class="form-control-plaintext">{{ user.last_name }}</div>
                    </div>
                </div>
                <div class="row mb-1 ms-3 border-bottom pb-3">
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">Email</label>
                        <div class="form-control-plaintext">{{ user.email }}</div>
                    </div>
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">Username</label>
                        <div class="form-control-plaintext">{{ user.username }}</div>
                    </div>
                </div>
                <div class="row mb-1 ms-3">
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">Country</label>
                        <div class="form-control-plaintext">{{ profile.country }}</div>
                    </div>
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">City</label>
                        <div class="form-control-plaintext">{{ profile.city }}</div>
                    </div>
                </div>
                <div class="row mb-1 ms-3">
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">Phone Number</label>
                        <div class="form-control-plaintext">{{ profile|phone_format }}</div>
                    </div>
                    <div class="col col-6">
                        <label class="form-label h6 text-secondary mb-1">Date Joined</label>
                        <div class="form-control-plaintext">{{ user.date_joined }}</div>
                    </div>
                </div>
            </div>
            <div class="col col-4">
                <h2 class="display-2">Photo</h2>
                <div class="d-flex justify-content-center align-items-center h-100">
                    {% if not profile.profile_picture %}
                        <img src="{% static 'images/random person.png' %}" class="img-fluid mb-3" alt="Default Profile Picture">
                    {% else %}
                        <img src="{{ profile.profile_picture.url }}" class="img-fluid mb-3" alt="Profile Picture">
                    {% endif %}
                </div>
            </div>
        </div>
        
        <div class="col col-8 list-group">
            <div class="h2 border-bottom pb-3 display-2">Social Links</div>
            {% for link in site_links %}
                <a href="{{ link.url }}" class="list-group-item list-group-item-action" target="_blank">
                    <h5 class="mb-1">{{ link.name }}</h5>
                    <p class="mb-1">{{ link.description }}</p>
                </a>
            {% empty %}
                <p>No site links available.</p>
            {% endfor %}
        </div>
    </div>
    <div class="d-flex gap-2 mb-3 justify-content-center">
        <a href="{% url 'users:update_profile' %}" class="btn btn-primary btn-lg">Edit Profile</a>
        <a href="#" class="btn btn-secondary btn-lg">Change Password</a>
    </div>

</div>
{% endblock main_content %}

apps/users/templates/users/update_profile.html
{% extends "users/after_login_base.html" %}
{% load static %}
{% load phone_number_extras %}

{% block main_content %}

<form method="post" id="linksForm" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="container-lg border border-3 rounded-5 p-4 mx-auto bg-light mt-4 mb-4" style="min-height: 60vh;">
        <div class="container-lg border border-3 rounded-5 p-4 mx-auto bg-white m-4">
            <div class="row mb-3">
                <div class="col col-8">
                    <h2 class="border-bottom pb-3 mb-3 display-2">
                        Account Information
                    </h2>
                    <div class="row mb-1 ms-3">
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1" for="id_first_name">First Name</label>
                            <input type="text" id="id_first_name" name="first_name" class="form-control w-75" value="{{ user.first_name }}">
                        </div>
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1" for="id_last_name">Last Name</label>
                            <input type="text" id="id_last_name" name="last_name" class="form-control w-75" value="{{ user.last_name }}">
                        </div>
                    </div>
                    <div class="row mb-1 ms-3 border-bottom pb-3">
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1" for="id_email">Email</label>
                            <input class="form-control w-75" type="text" placeholder="{{ user.email }}" disabled>
                        </div>
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1">Username</label>
                            <input class="form-control w-75" type="text" placeholder="{{ user.username }}" disabled>
                        </div>
                    </div>
                    <div class="row mb-1 ms-3">
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1" for="id_country">Country</label>
                            <input type="text" id="id_country" name="country" class="form-control w-75" value="{{ second_form.country.value }}">
                        </div>
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1" for="id_city">City</label>
                            <input type="text" id="id_city" name="city" class="form-control w-75" value="{{ second_form.city.value }}">
                        </div>
                    </div>
                    <div class="row mb-1 ms-3">
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1" for="id_phone">Phone Number</label>
                            <input type="text" id="id_phone" name="phone_number" class="form-control w-75" value="{{ second_form.phone_number.value }}">
                        </div>
                        <div class="col col-6">
                            <label class="form-label h6 text-secondary mb-1">Date Joined</label>
                            <input class="form-control w-75" type="datetime" placeholder="{{ user.date_joined }}" disabled>
                        </div>
                    </div>
                </div>
                <div class="col col-4">
                    <h2 class="display-2">Photo</h2>
                    <div class="d-flex flex-column justify-content-center align-items-center h-100">
                        <img id="profilePreview" src="{% if second_form.instance.profile_picture %}{{ second_form.instance.profile_picture.url }}{% else %}{% static 'images/random_person.png' %}{% endif %}" 
                            data-default-src="{% static 'images/random_person.png' %}" 
                            class="img-fluid mb-3" alt="Profile Picture">
                        <div class="d-flex gap-2">
                            <!-- Select new photo -->
                            <input type="file" id="id_profile_picture" name="profile_picture" accept="image/*" style="display: none;">
                            <button type="button" class="btn btn-outline-primary" id="selectPhotoBtn" for="id_profile_picture">
                                Select New Photo
                            </button>

                            <!-- Remove current photo -->
                            <button type="button" class="btn btn-outline-danger" id="removePhotoBtn">Remove Photo</button>
                        </div>
                    </div>
                </div>
            </div>
            
        </div>
        <div class="d-flex align-items-center justify-content-between mb-2 toggle-details" 
            data-bs-toggle="collapse" href="#collapseExample" role="button" 
            aria-expanded="false" aria-controls="collapseExample" id="toggleDetails">
            <span>
                <i id="arrowIcon" class="bi bi-caret-right"></i>
                Social Links
            </span>
            <hr class="flex-grow-1 ms-2 my-0">
        </div>
    
        <div class="collapse" id="collapseExample">
            <div class="container-lg border rounded-5 p-4 bg-white mb-2">

                <div class="col col-12 list-group">
                    <div class="h2 border-bottom pb-3 display-2">Social Links</div>
                    {{ formset.management_form }}
                    {% if formset.forms|length == 0 %}
                        <p>No items available.</p>
                    {% else %}
                    <table class="table table-sm table-hover mb-3">
                        <colgroup>
                            <col style="width: 20%;">
                            <col style="width: 35%;">
                            <col style="width: 35%;">
                            <col style="width: 10%;">
                        </colgroup>
                        <thead>
                            <tr>
                                <th scope="col">Name</th>
                                <th scope="col">URL</th>
                                <th scope="col">Description</th>
                                <th scope="col">Delete</th>
                            </tr>
                        </thead>
                        <tbody id="formsetTable">
                            {% for form in formset %}
                                <tr>
                                    {{ form.id }}
                                    <td>
                                        <input type="text" class="form-control form-control-sm text-truncate" name="{{ form.name.html_name }}" value="{{ form.name.value }}">
                                    </td>
                                    <td>
                                        <input type="url" class="form-control form-control-sm text-truncate" name="{{ form.url.html_name }}" value="{{ form.url.value }}">

                                    </td>
                                    <td>
                                        <input type="text" class="form-control form-control-sm description-field" name="{{ form.description.html_name }}" value="{{ form.description.value }}">
                                    </td>
                                    <td class="text-center">
                                        {% if formset.can_delete %}
                                            <input type="checkbox" class="form-check-input" name="{{ form.prefix }}-DELETE" id="id_{{ form.prefix }}-DELETE">
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                    <div class="d-flex gap-2 justify-content-center">
                        <button type="button" class="btn btn-sm btn-outline-secondary" id="addRow">➕ Add Row</button>
                        <button type="button" class="btn btn-sm btn-outline-danger remove-row" id="removeLastRow">Remove</button>
                    </div>
                </div>

            </div>
        </div>
        <div class="d-flex gap-2 justify-content-center">
            <button type="submit" class="btn btn-lg btn-primary">Save</button>
        </div>
    </div>

    <!-- Hidden template for new rows -->
    <template id="emptyFormTemplate">
        <tr class="form-row">
            <td>
                <input type="text" class="form-control form-control-sm text-truncate" 
                    name="form-__prefix__-name" value="">
            </td>
            <td>
                <input type="url" class="form-control form-control-sm text-truncate" 
                    name="form-__prefix__-url" value="">
            </td>
            <td>
                <input type="text" class="form-control form-control-sm description-field" 
                    name="form-__prefix__-description" value="">
            </td>
            <td></td>
        </tr>
    </template>

</form>

<script src="{% static 'users/js/user_update.js' %}"></script>
<script src="{% static 'js/collapse_container.js' %}"></script>

{% endblock main_content %}